# Generated by Django 3.2 on 2021-04-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Golongan', models.CharField(blank=True, max_length=10)),
                ('Nominal', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Pegawai', models.CharField(blank=True, max_length=20)),
                ('Nama_Guru', models.CharField(blank=True, max_length=100)),
                ('No_Hp', models.DecimalField(decimal_places=0, max_digits=13)),
                ('Alamat', models.CharField(blank=True, max_length=100)),
                ('Golongan_PNS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guru.gaji')),
            ],
        ),
    ]
