# Generated by Django 3.2 on 2021-04-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0001_initial'),
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='Golongan_PNS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tatausaha.gaji'),
        ),
        migrations.DeleteModel(
            name='Gaji',
        ),
    ]
