# Generated by Django 3.2 on 2021-04-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0004_alter_guru_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guru',
            name='Golongan_PNS',
        ),
        migrations.RemoveField(
            model_name='guru',
            name='No_Pegawai',
        ),
        migrations.RemoveField(
            model_name='guru',
            name='id',
        ),
        migrations.RemoveField(
            model_name='guru',
            name='kelas',
        ),
        migrations.AddField(
            model_name='guru',
            name='Gaji',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='Kelas',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='nip',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guru',
            name='Alamat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='Nama_Guru',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guru',
            name='No_Hp',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
