# Generated by Django 3.2 on 2021-04-26 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0006_auto_20210426_0003'),
        ('guru', '0005_auto_20210426_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='Gaji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tatausaha.gaji'),
        ),
    ]
