# Generated by Django 3.2 on 2021-04-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0010_delete_tampiljadwalpelajaran'),
        ('guru', '0007_alter_guru_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id_absen', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('kehadiran', models.CharField(max_length=2)),
                ('keterangan', models.CharField(max_length=50)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tatausaha.kelas')),
            ],
        ),
    ]
