# Generated by Django 3.2 on 2021-04-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0008_absensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='keterangan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
