# Generated by Django 3.2 on 2021-04-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0014_mapel_jumlah_pertemuan'),
        ('guru', '0009_alter_absensi_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='Mapel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tatausaha.mapel'),
        ),
    ]
