# Generated by Django 3.2 on 2021-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Golongan', models.CharField(blank=True, max_length=10)),
                ('Nominal', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
    ]
