# Generated by Django 3.2 on 2021-04-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kode_Mapel', models.CharField(max_length=6)),
                ('Nama_MataPelajaran', models.CharField(max_length=20)),
                ('Jam', models.CharField(max_length=12)),
                ('Guru_Pengampu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tatausaha.gaji')),
            ],
        ),
    ]
