# Generated by Django 3.2 on 2021-04-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0002_matapelajaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaji',
            name='Nominal',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
