# Generated by Django 3.2 on 2021-04-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0002_auto_20210414_1440'),
        ('tatausaha', '0003_alter_gaji_nominal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajaran',
            name='Guru_Pengampu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru.guru'),
        ),
    ]
