# Generated by Django 3.2 on 2021-04-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0005_auto_20210424_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id_mapel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nama_Pelajaran', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='gaji',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='jam',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='mata_pelajaran',
        ),
        migrations.AlterField(
            model_name='gaji',
            name='Golongan',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
