# Generated by Django 3.2 on 2021-04-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0008_jadwalpelajaran_jam_pelajaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='TampilJadwalPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kelas', models.CharField(max_length=5)),
                ('Mapel', models.CharField(max_length=50)),
            ],
        ),
    ]
