# Generated by Django 3.2 on 2021-04-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0009_tampiljadwalpelajaran'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TampilJadwalPelajaran',
        ),
    ]
