# Generated by Django 3.2 on 2021-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0010_delete_tampiljadwalpelajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='keterangan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
