# Generated by Django 3.2 on 2021-04-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0011_nilai_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='keterangan',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
