# Generated by Django 3.2 on 2021-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0013_alter_nilai_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapel',
            name='Jumlah_Pertemuan',
            field=models.CharField(default='', max_length=3),
        ),
    ]
