# Generated by Django 3.2 on 2021-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0014_mapel_jumlah_pertemuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalpelajaran',
            name='hari',
            field=models.CharField(default='', max_length=7),
        ),
    ]
