# Generated by Django 3.2 on 2021-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0015_jadwalpelajaran_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalpelajaran',
            name='hari',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], default='Minggu', max_length=7),
        ),
    ]
