# Generated by Django 3.2 on 2021-04-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0017_auto_20210428_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalpelajaran',
            name='Jumlah_Pertemuan',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
