# Generated by Django 3.2 on 2021-04-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Ruangan', models.CharField(blank=True, max_length=20)),
                ('Kapasitas_Ruangan', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nis', models.CharField(blank=True, max_length=10)),
                ('Nama', models.CharField(blank=True, max_length=100)),
                ('Jam_Pelajaran', models.CharField(blank=True, max_length=11)),
                ('No_Hp', models.CharField(blank=True, max_length=13)),
                ('Alamat', models.CharField(blank=True, max_length=100)),
                ('Nama_Ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='murid.ruangan')),
            ],
        ),
    ]
