# Generated by Django 3.2 on 2021-04-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0002_matapelajaran'),
        ('murid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='murid',
            name='Mata_Pelajaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tatausaha.matapelajaran'),
        ),
    ]
