# Generated by Django 3.2 on 2021-04-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0002_murid_mata_pelajaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murid',
            name='Jam_Pelajaran',
        ),
        migrations.AddField(
            model_name='ruangan',
            name='SiswaDiRuangan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='murid.murid'),
        ),
    ]
