# Generated by Django 3.2 on 2021-04-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0003_auto_20210414_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangan',
            name='SiswaDiRuangan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='murid.murid'),
        ),
    ]
