# Generated by Django 3.2 on 2021-04-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0005_remove_ruangan_siswadiruangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='SiswaDiRuangan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='murid.murid'),
        ),
    ]
