# Generated by Django 3.2 on 2021-04-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0006_ruangan_siswadiruangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruangan',
            name='SiswaDiRuangan',
        ),
    ]
