# Generated by Django 3.2 on 2021-04-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0008_auto_20210414_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murid',
            name='Mata_Pelajaran',
        ),
        migrations.RemoveField(
            model_name='murid',
            name='Nama_Ruangan',
        ),
        migrations.AddField(
            model_name='murid',
            name='Kelas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Ruangan',
        ),
    ]
