# Generated by Django 3.2 on 2021-04-24 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0005_auto_20210424_0833'),
        ('murid', '0009_auto_20210424_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murid',
            name='Kelas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tatausaha.kelas'),
        ),
    ]
