# Generated by Django 3.2 on 2021-04-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0010_alter_murid_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murid',
            name='id',
        ),
        migrations.AlterField(
            model_name='murid',
            name='Alamat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='murid',
            name='Kelas',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='murid',
            name='Nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='murid',
            name='Nis',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='murid',
            name='No_Hp',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
