# Generated by Django 3.2 on 2021-04-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatausaha', '0006_auto_20210426_0003'),
        ('murid', '0011_auto_20210426_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murid',
            name='Kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tatausaha.kelas'),
        ),
    ]
